// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZlLnL6kdh6spBlH9xUx0fSTMx2V4-0I',
    appId: '1:102785330393:web:f8c8932ca9f1067d6c22c8',
    messagingSenderId: '102785330393',
    projectId: 'the-reserve-mobile',
    authDomain: 'the-reserve-mobile.firebaseapp.com',
    storageBucket: 'the-reserve-mobile.appspot.com',
    measurementId: 'G-LJV4CK91V9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZlLnL6kdh6spBlH9xUx0fSTMx2V4-0I',
    appId: '1:102785330393:web:bed7f736b9e9e7626c22c8',
    messagingSenderId: '102785330393',
    projectId: 'the-reserve-mobile',
    authDomain: 'the-reserve-mobile.firebaseapp.com',
    storageBucket: 'the-reserve-mobile.appspot.com',
    measurementId: 'G-XNCP86V76P',
  );
}
